[package]
name = "sc19-rust-client"
version = "0.1.0"
authors = ["fwcd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
serde = "1.0.101"
serde-xml-rs = "0.3.1"
log = "0.4.8"
simplelog = "0.7.3"
